# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_id', models.IntegerField(unique=True)),
                ('major', models.CharField(max_length=50)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='union.Union')),
            ],
        ),
    ]
