# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0004_auto_20170522_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 22, 2, 11, 10, 436769, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
