# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('union', '0006_auto_20170522_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(unique=True),
        ),
    ]
