# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0007_auto_20170522_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='people',
        ),
        migrations.AddField(
            model_name='union',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
